apiVersion: v1
kind: Pod
metadata:
 name: master-nginx
 labels:
  app: master-nginx
spec:
 containers:
 - name: nginx
   image: smulani888/cloudethix_master_nginx_sameer:v2
   ports:
   - containerPort: 80




